Readme changes
akretion/docky pull request #133
Opened 2020-03-31 15:50 UTC by kevinkhao

2020-03-31 15:58 UTC, rvalyi requested changes

2020-03-31 15:58 UTC, rvalyi commented on README.rst
>  docky : Make docker and docker-compose simply !
this 1st sentence is non English, this is bad to frighten international users right at the start.
I propose to simply remove it, as the next sentence is a good introduction.

2020-03-31 16:33 UTC, bealdav approved these changes

2020-04-02 07:26 UTC, hparfr approved these changes

2020-04-02 07:27 UTC, merged